gfxstream: look for common/opengl headers
Probably "Make GL header lib and update libs to explicitly
depend on it" broke the meson build.

In file included from ../renderControl_enc/renderControl_types.h:19,
                 from ../renderControl_enc/renderControl_client_proc.h:8,
                 from ../renderControl_enc/renderControl_client_context.h:6,
                 from ../renderControl_enc/renderControl_enc.h:9,
                 from ../vulkan_enc/../OpenglSystemCommon/HostConnection.h:25,
                 from ../vulkan_enc/ResourceTracker.cpp:19:
../OpenglCodecCommon/glUtils.h:46:10: fatal error: GLES/gl.h: No such file or directory

Long term, we should nuke renderControl and GL dependencies through
compile options (GOLDFISH_NO_GL) for example.

     ninja -C amd64-build

Reviewed-by: Aaron Ruby <aruby@blackberry.com>
Acked-by: Yonggang Luo <luoyonggang@gmail.com>
Acked-by: Adam Jackson <ajax@redhat.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27246>